elasticsearch     = 7.10.2
lucene            = 9.12.0

bundled_jdk_vendor = openjdk
bundled_jdk = 17.0.9+9

checkstyle = 8.20

# optional dependencies
spatial4j         = 0.7
jts               = 1.15.0
jackson           = 2.10.4
snakeyaml         = 1.26
icu4j             = 62.1
supercsv          = 2.4.0
log4j             = 2.11.1
slf4j             = 1.6.2

jna               = 5.5.0

netty             = 4.1.49.Final
joda              = 2.10.4

bouncycastle=1.64
# test dependencies
randomizedrunner  = 2.7.1
junit             = 4.12
httpclient        = 4.5.10
httpcore          = 4.4.12
httpasyncclient   = 4.1.4
commonslogging    = 1.1.3
commonscodec      = 1.11
hamcrest          = 2.1
securemock        = 1.2
mocksocket        = 1.2

# benchmark dependencies
jmh               = 1.19
